name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'
    - 'requirements.txt'
    - 'Dockerfile'
    - '.github/workflows/cicd.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/ci-cd.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover tests

      - name: Build Docker image
        run: |
          docker build -t futures-stock-info .

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rekam/futures-stock-info:latest